### ISSUE TITLE
Error in Nespresso.py in 2024.04.01

### ISSUE THREAD

**Issue by nxor** [bulldog5046/ha_nespresso_ingetration#18]
Error in onboard probably link to new python (2024.4.1)

I needed to remove the check for dbus_error

new code :
    async def onboard(self, client: BleakClient):
        try:
            # Write the txLevel to LOW
            await client.write_gatt_char(CHAR_UUID_PAIR, bytearray([1]), response=True)
            # Write the auth code
            await client.write_gatt_char(CHAR_UUID_AUTH, binascii.unhexlify(self.auth_code), response=True)
        except Exception as e:
            _LOGGER.error('Onboarding not permitted. Already paired?')

**Comment by nxor** [comment]
I did more test and added some debug info and now I get this : 
2024-04-06 10:11:27.638 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/nespresso/nespresso.py", line 230, in onboard
    await client.write_gatt_char(CHAR_UUID_AUTH, binascii.unhexlify(self.auth_code), response=True)
  File "/usr/local/lib/python3.12/site-packages/bleak/__init__.py", line 776, in write_gatt_char
    await self._backend.write_gatt_char(characteristic, data, response)
  File "/usr/local/lib/python3.12/site-packages/bleak/backends/bluezdbus/client.py", line 834, in write_gatt_char
    reply = await self._bus.call(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dbus_fast/aio/message_bus.py", line 384, in call
    await future
  File "src/dbus_fast/aio/message_reader.py", line 19, in dbus_fast.aio.message_reader._message_reader
  File "src/dbus_fast/_private/unmarshaller.py", line 777, in dbus_fast._private.unmarshaller.Unmarshaller._unmarshall
  File "src/dbus_fast/_private/unmarshaller.py", line 638, in dbus_fast._private.unmarshaller.Unmarshaller._read_header
  File "src/dbus_fast/_private/unmarshaller.py", line 374, in dbus_fast._private.unmarshaller.Unmarshaller._read_to_pos
  File "src/dbus_fast/_private/unmarshaller.py", line 317, in dbus_fast._private.unmarshaller.Unmarshaller._read_sock_with_fds
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 107, in _async_start
    await gather_with_limited_concurrency(FLOW_INIT_LIMIT, *init_coros)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 207, in gather_with_limited_concurrency
    return await gather(
           ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 205, in sem_task
    return await task
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1155, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1185, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 506, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nespresso/config_flow.py", line 94, in async_step_bluetooth
    await device.connect(ble_device)
  File "/config/custom_components/nespresso/nespresso.py", line 99, in connect
    await self.onboard(client)
  File "/config/custom_components/nespresso/nespresso.py", line 232, in onboard
    if e.dbus_error == 'org.bluez.Error.NotPermitted':
       ^^^^^^^^^^^^
AttributeError: 'EOFError' object has no attribute 'dbus_error'
